### ISSUE TITLE
RNZoomUs not in Native Modules

### ISSUE THREAD

**Issue by dcoellarb** [mieszko4/react-native-zoom-us#10]
Hi my aplication in on React native 0.61.2, i follow the instructions but the the RNZoomUs not being add to Native Modules, import ZoomUs from 'react-native-zoom-us'; returns null, i believe it might have something to do with new automatic linking of react native > .60, i did run react-native link react-native-zoom-us but same result

Thanks in advance for any help on this

**Comment by mieszko4** [comment]
I would need to take a close look on that, maybe over the weekend.
I also believe that the problem is with automatic linking in rn > 0.60

**Comment by KawaljeetSBagga** [comment]
Any update?

**Comment by gHashTag** [comment]
Please update the library. This is a very current library at the moment.

**Comment by amdrade** [comment]
This error occurs because rn> 0.59 uses autolink for libraries with CocoaPods and the files are in a different location in the project.
I resolved it as follows:

- First update SDK zoom to last version
- Move file `react-native-zoom-us/ios/RNZoomUs.podspec` to `react-native-zoom-us/RNZoomUs.podspec`
- Change `s.source_files` to ` "ios/**/*.{h,m}"`
- Add `s.libraries = "sqlite3", "z.1.2.5", "c++"`
- Add `s.vendored_frameworks = "ios/libs/MobileRTC.framework", "ios/libs/MobileRTCScreenShare.framework"`
- `cd ios` and `pod install`
- Change the imports of the headers in the SDK, `<MobileRTC/MobileRTC.h>` to `<MobileRTC.h>`. You can find "`MobileRTC/`" and replace with nothing "" and recompile.

Some of the extra steps still need to be done as well, the ones that are needed.

**Comment by mieszko4** [comment]
I will close that for now. Please check with version 5 of the package (it is breaking changes though).
If issue will appear again feel free to reopen it.

**Comment by sumeetHalder** [comment]
Using RN version:.0.62 and react-native-zoom-us:5.9.0.., still facing the issue "RNZoomUs Native Modules is not linked".., any update on this, please update if their is any plan for this fix

**Comment by mieszko4** [comment]
This is a very old thread. Please check if you can build with example app https://github.com/mieszko4/react-native-zoom-us-test

**Comment by Abhinav1762** [comment]
Using RN version:.0.68.2 and react-native-zoom-us:6.15.0.., still facing the issue "RNZoomUs Native Modules is not linked".., any update on this, please update if their is any plan for this fix

**Comment by mieszko4** [comment]
Please try with newest `6.16.5`.

**Comment by AdityaChaudhary1** [comment]
> Please try with newest `6.16.5`.
 still facing same issue
