### ISSUE TITLE
Upgrading the android native sdk

### ISSUE THREAD

**Issue by rafi16jan** [mieszko4/react-native-zoom-us#111]
Hello this is a great project, big appreciation for your hard work. I'm wondering something, can you give insights about upgrading the native sdk especially the android one? (since it's a little bit too old) or did you have any technical reasons why didn't you upgrade the android version yet? I'm currently tasked to upgrade the android sdk so I might be writing a PR

**Comment by mieszko4** [comment]
hi @rafi16jan the upgrade for android has been done with https://github.com/mieszko4/react-native-zoom-us/pull/107
It is on version `6.0.2` of this package.

I had some difficulties with upgrading - gradle build failing because of some issues with aar.

@zvs001 did the upgrade - moving to jitpack.io the .aar files.

**Comment by rafi16jan** [comment]
Niceee... wow didn't knew upgrading was that challenging. How stable is the 6.0.2 version?

**Comment by mieszko4** [comment]
I've did the smoke test (https://github.com/mieszko4/react-native-zoom-us-test#smoke-test-procedure) - no issues. Other than that I think it should be stable.
