### ISSUE TITLE
Question about SDK keys

### ISSUE THREAD

**Issue by kotoyama** [mieszko4/react-native-zoom-us#127]
Hi, thanks for your work!
I'm building an app where students can join in the existing meeting.
The question is how to initialize Zoom SDK correctly - is it enough to use one SDK Key & Secret pair for multiple users to generate JWT tokens for each one? Or should I need separate SDK Key & Secret pairs for each user?
It would be great if you could clarify.

**Comment by mieszko4** [comment]
Hi, thnx! I got some great contributors :)

Good question, but I am not really sure I know the correct answer.
If I were doing it I would generate a separate JWT per mobile app user (i.e. per each student)
It would simply be easier for me to follow since each JWT has an expiration date. (unless there is some limit for JWT tokens)

So on app init I would call my API which would return a JWT for me - so that sdk key & secret pair is not stored on the app but on the backend.

But honestly I am not sure if that's the right approach. I would look for information on how to approach it using nativse zoom sdk or zoom ios

**Comment by mieszko4** [comment]
I will close that now
