### ISSUE TITLE
[Android] Automate copying of *.aar files

### ISSUE THREAD

**Issue by mieszko4** [mieszko4/react-native-zoom-us#257]

**Comment by chirag-codealchemy** [comment]
i provided direct download link 
> # commonlib
> https://drive.google.com/uc?id=1DwiLIKdVY5kUIsGTM7N7yNqciGtBhZTz&export=download

> # mobilertc
> https://drive.google.com/uc?id=1dsMeynPPXayfZWxloauLxLWOo2ewUR2K&export=download&confirm=t

**Comment by cloudy-ninja** [comment]
Hi @mieszko4, @chirag-codealchemy our zoom lib is working perfectly on dev, but on release mode I am getting the following error. I am not sure if this error is happening due to using of local aar files. If so, can we use google drive links?

`Direct local .aar file dependencies are not supported when building an AAR. The resulting AAR would be broken because the classes and Android resources from any local .aar file dependencies would not be packaged in the resulting AAR. Previous versions of the Android Gradle Plugin produce broken AARs in this case too (despite not throwing this error). The following direct local .aar file dependencies of the :react-native-zoom-us project caused this error:`

**Comment by cloudy-ninja** [comment]
In that case, can you please let me know how I can update the build gralde to use google drive links?

**Comment by mieszko4** [comment]
I see, we should try back jitpack then. I initially wanted to do that but LFS is exceeded on repo, I created an issue for @zvs001 https://github.com/zoom-us-community/jitpack-zoom-us/issues/11.

@chirag-codealchemy Idea with using google drive sounds good but I think we should stick to jitpack to avoid any quota limits etc. And we already had it working with jipack so it should work again once new version is uploaded to https://github.com/zoom-us-community/jitpack-zoom-us and the lib adjusted back to what it was

**Comment by mieszko4** [comment]
It is done in newest `6.16.5` which uses jitpack again. Also updated [test app](https://github.com/mieszko4/react-native-zoom-us-test).

**Comment by cloudy-ninja** [comment]
Thank you so much for your works @mieszko4
