### ISSUE TITLE
Regarding Upgrade Plans

### ISSUE THREAD

**Issue by vasanimit9** [mieszko4/react-native-zoom-us#266]
Hi.

According to [this](https://support.zoom.us/hc/en-us/articles/360059429231-Zoom-Software-Quarterly-Lifecycle-Policy), the iOS SDK currently being used by this package will be outdated soon. Are there any plans to upgrade the iOS SDK?

Thanks!

**Comment by mieszko4** [comment]
Thnx for the link! I see that the next enforcement for `Meeting SDK (Native)` is `May 6, 2023`:
* 5.11.3 (Android, iOS)

We currently use `5.11.3` (iOS) and `5.13.1` (Android)

Hence we should be good till August because of Zoom's `Quarterly Lifecycle Policy`

The general plan is to keep it up to date and we should upgrade iOS to be in sync with Android.

I created https://github.com/mieszko4/react-native-zoom-us/issues/267 for now. I could try that after 2 weeks.
