### ISSUE TITLE
Support for `startShareViewContent()`?

### ISSUE THREAD

**Issue by matallui** [mieszko4/react-native-zoom-us#287]
Hi! I'm trying to figure out a way of sharing content to Zoom via the Android SDK (and therefore this library, since I'm using RN). However, I'm not interested in sharing the screen content of the android device, but instead I'd like to pick what `View` I'd like to share.

By looking at the [Zoom SDK documentation](https://developers.zoom.us/docs/meeting-sdk/android/use-meeting-sdk/custom-ui/share/#views-distribute-the-shared-view), it sounds like they have an API call for `startShareViewContent()` that lets you do just that, but it doesn't seem to be implemented by this package. Is there a reason why it isn't implemented? Would it be feasible to add this functionality?

I'm not a native Android dev, but I'm willing to submit a PR if this is a feasible feature.

**Comment by mieszko4** [comment]
> Is there a reason why it isn't implemented? Would it be feasible to add this functionality?

The reason is no time :)
I am open to new PR if you want to contribute.
I am also not a native Android developer so I am not sure how much I can help.

I am still not sure, however, if I understand this functionality and how you want to use it. You want to be able to share, e.g. in-app browser only?

We already have Custom UI implemented in `docs/VIDEO-VIEW.md` (Android only) so it looks like it could be maybe extended to support sharing.

**Comment by matallui** [comment]
Yeah, fair enough! Actually what I need is just a way to share a URL to the meeting, similar to what is done in the sample code above. So... I do have the code I would need, since the Android sample code has all that I need, just need to add the React Native API for it. I may open a PR at some point if I decide to proceed with this library.
