### ISSUE TITLE
Why are we not updating the SDK to the latest version.

### ISSUE THREAD

**Issue by ajayhcode** [mieszko4/react-native-zoom-us#288]
Why are we not updating the SDK to the latest version for android as well as IOS.
As that will resolve a lot of bugs and issues users are facing.
Is there any specific reason for not doing that or is it on purpose.
We can update the Android and IOS SDK to 5.15.5.
@mieszko4  @jcamins @mialy @hans00 @amdrade

**Comment by mieszko4** [comment]
We are currently 2 major versions behind - we use 5.13.X, latest is 15.15.X
Being always on latest version is a little bit risky because of possible breaking changes, unexpected bugs etc. but I agree that we should update to 15.4.X.
The main reason is, however, that I haven't had time to do that since it requires some time to implement, adjust breaking changes and run the tests on both iPhone and Android.

I am open for new PRs though :)
