### ISSUE TITLE
Upgrade zoom sdk to the latest version

### ISSUE THREAD

**Issue by orhsgfsf** [mieszko4/react-native-zoom-us#56]
Thanks for the awesome library.
Is there any possible way to upgrade the sdk to the latest version 5.4.x? because it supports virtual background for Android.
Thank you very much.

**Comment by juniorklawa** [comment]
+1

**Comment by mieszko4** [comment]
Thnx, yeah, I was thinking about updating it. I will try to do that these days.

**Comment by Alessandro1918** [comment]
Hello, awesome work you got going on here!

Any plans on updating the Android SDK version?
(Project currently @ 5.0.x, Zoom already made 5.7.x available)

While trying to run the demo code from [react-native-zoom-us-test](https://github.com/mieszko4/react-native-zoom-us-test), I got a crypt message of `ERROR [Error: Error: 4, internalErrorCode=0]`  and opened an issue reporting [here](https://github.com/mieszko4/react-native-zoom-us-test/issues/27). 

I just now found [this zoom page](https://zoom.github.io/zoom-sdk-android/us/zoom/sdk/MeetingError.html) that made me think this error is because of a low client version. Can you check if it´s really that case?

Thanks!

**Comment by mieszko4** [comment]
Upgrade of android sdk was done by @zvs001 - check version 6.0.1 with android sdk version 5.7.
